### ISSUE TITLE
compartment model (SEIR) example request

### ISSUE THREAD

**Issue by yijunwang0805** [junpenglao/advance-bayesian-modelling-with-PyMC3#1]
Dear Lao,

Given that COVID-19 starts to impact countries globally, people have grown interest in using epidemic models to model COVID 19 infectious. 

Could you please share an example of the compartment (SEIR) model in PyMC3? That is, using MCMC to estimate the parameters in SEIR model.

I have been looking around online, but haven't found an example that actually work.

Best regards,
Yijun

**Comment by junpenglao** [comment]
@Dpananos started to work on it in https://github.com/Dpananos/WuhanFlu

**Comment by yijunwang0805** [comment]
Thank you very much!

**Comment by yijunwang0805** [comment]
Hi, Dpananos' github hasn't updated for four months. I wonder how would this go. Any suggestion?

**Comment by Dpananos** [comment]
If you're interested in doing ODE inference in PyMC3, have a look at [`DifferentialEquation`](https://docs.pymc.io/notebooks/ODE_API_introduction.html).  The SEIR model has many variants, and I'm not sure which variant you're interested in looking at.  Consequently, I can't really advise on how to implement without more details and can only point you towards the documentation.

**Comment by junpenglao** [comment]
@yijunwang0805 There are multiple effort on modeling SEIR like model, you should check out:
https://github.com/Priesemann-Group/covid19_inference_forecast/
https://github.com/Priesemann-Group/covid19_inference/
You can find some minimal example to illustrate the idea here: https://discourse.pymc.io/t/how-to-sample-efficiently-from-time-series-data/4928/3?u=junpenglao
